# Generated by Django 5.2.1 on 2025-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightoffer',
            name='airline',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='flightoffer',
            name='currency',
            field=models.CharField(max_length=5),
        ),
    ]
