# Generated by Django 5.2.1 on 2025-06-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_alter_flightoffer_airline_alter_flightoffer_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightoffer',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
